### ISSUE TITLE
ModPol compatibility

### ISSUE THREAD

**Issue by tacotexmex** [CodeScratcher/factions-mod#7]
Because of the feature overlap, would it be interesting to add support for or roll this mod into [ModPol](https://content.minetest.net/packages/ntnsndr/modpol/)?

**Comment by CodeScratcher** [comment]
Possibly. I would have to do more testing to see how it overlaps.

**Comment by CodeScratcher** [comment]
Looking more into it, I feel like cooperative factions should remain a separate mod. Cooperative factions is small. It fulfills a niche, where as Modpol is much larger and much more complicated.
