### ISSUE TITLE
Broken mod

### ISSUE THREAD

**Issue by Usman281** [CodeScratcher/factions-mod#8]
Test sorry

**Comment by CodeScratcher** [comment]
give more info, how is it broken

**Comment by Usman281** [comment]
When the mod is added you already in a faction

**Comment by CodeScratcher** [comment]
That is intended behavior, the "neutral" faction is meant to act as the default faction, or the faction for players who don't have a faction. It's easier to have a default faction than to have no faction, with the way our code is set up.
